### ISSUE TITLE
Set up JSON data storage & create module for storage

### ISSUE THREAD

**Issue by MichaelHopwood** [mantzaris/Tagasaurus#3]
```
{
  { image: image_location,
    description: "i like bunnies",
    tag: "I", "bunnies",
    triple: ("I","like","bunnies"),
    emotion: happy,
    meme: meme_location,
  }
}
```

**Comment by mantzaris** [comment]
That is a great data design. Tomorrow I hope to get to the bottom of the issue of the CSS that I have. I am thinking of sticking with Bootstrap regardless of the issue Randyll and I had with it

**Comment by mantzaris** [comment]
One point, is that the emotions, need to be an array of the emotional value types and a numerical value for each one from zero to one. Which is then stored as a normalized value set.

**Comment by randyll** [comment]
Hi Alex,
Michael and I met today and we have a plan to sort out the interface so we have that covered for you.

Kind regards,
Randyll


On Apr 4, 2021, at 9:04 PM, a.v.mantzaris ***@***.***> wrote:

﻿

That is a great data design. Tomorrow I hope to get to the bottom of the issue of the CSS that I have. I am thinking of sticking with Bootstrap regardless of the issue Randyll and I had with it

**Comment by mantzaris** [comment]
That is Great news!

**Comment by mantzaris** [comment]
added the ability for the user to enter a description, for the some stop words to be removed, and then display the filtered result as a list to the user. Button functionality is there so that iterations on the algorithmics can be done

**Comment by mantzaris** [comment]
the emotions are added as an array which may be a bit of an excess to store the spare array but even though in terms of storage it is not a good idea it will make things a bit easier to pass around the full set of attributes

**Comment by mantzaris** [comment]
Now the way the JSON data is stored internally needs to be thought through. The JSON is important for the storage but prior to that the use of dictionaries should likely be a candidate. 

Any ideas?

**Comment by mantzaris** [comment]
Ok, so sqlite is connected. I gave up on Dexie (wrapper of IndexedDB), as the nature of the indices and the query style although it looks awesome, was just too outlandish for the expectation of rigid RDBMS paradigms... maybe for a later version. Need to clean the code and simplify it for sure and reduce the unnecessary printing statements. Then the design needs some thought.

**Comment by mantzaris** [comment]
Question: do you think we should also be storing the full 'raw' photo description or only the tag list we infer?
